### ISSUE TITLE
maud_lints panics when using a Fn, FnOne or FnMut argument

### ISSUE THREAD

**Issue by abdullahibnnadjo** [lfairy/maud#112] opened 2017-12-03 15:55 UTC
On branch better-lints:

Consider this:
```rust
#[test]
fn lint_closure() {
    fn notice<F>(note_fn: F)
        where F: FnOnce() -> String
    {
        let to_log = note_fn();
        println!("Notice: {}", to_log);
    }

    notice(|| html! { event "Started" }.into_string());
}
```
with `#![plugin(maud_lints)]`, causes:

`error: internal compiler error: /checkout/src/librustc/hir/def.rs:166: attempted .def_id() on invalid def: Local(NodeId(115))`.

This is due to https://github.com/lfairy/maud/blob/1cf6a13966667739cc03b7df167ee294ec51f8c2/maud_lints/src/maud_lint.rs#L29 trying to call `def_id()` on a Fn argument, which is a NodeId.

I really don't know much about Rust HIR, so I may be missing something ?

**Comment by lfairy** [comment] 2017-12-16 00:18
My best guess is it's trying to find the definition of the closure's type, which fails because closure types are anonymous.

I admit I don't know much about HIR either. Most of that code was copied from Clippy a while ago.

If you have the time, can you please check how Clippy finds the definition for a type? It's likely that Clippy has fixed this issue themselves already.

**Comment by lfairy** [comment] 2018-05-18 09:16
I can't reproduce this with the current `master`. Closing as fixed.

**Closed by lfairy** 2018-05-18 09:16 UTC
Labels: bug, difficulty: easy
