### ISSUE TITLE
Error compiling Maud - cargo 1.31.0-nightly (ad6e5c003 2018-09-28)

### ISSUE THREAD

**Issue by viadata** [lfairy/maud#153] opened 2018-10-10 09:27 UTC
Hi there,
Getting this error on adding maud to the dependencies on a fresh project:
```
   Compiling maud_macros v0.18.1
error[E0557]: feature has been removed
 --> /home/shannon/.cargo/registry/src/github.com-1ecc6299db9ec823/maud_macros-0.18.1/src/lib.rs:2:12
  |
2 | #![feature(proc_macro_non_items)]
  |            ^^^^^^^^^^^^^^^^^^^^
  |
note: subsumed by `#![feature(proc_macro_hygiene)]`
 --> /home/shannon/.cargo/registry/src/github.com-1ecc6299db9ec823/maud_macros-0.18.1/src/lib.rs:2:12
  |
2 | #![feature(proc_macro_non_items)]
  |            ^^^^^^^^^^^^^^^^^^^^

error[E0658]: procedural macros cannot be expanded to expressions (see issue #54727)
  --> /home/shannon/.cargo/registry/src/github.com-1ecc6299db9ec823/maud_macros-0.18.1/src/generate.rs:67:21
   |
67 |                     quote!($head $body)
   |                     ^^^^^^^^^^^^^^^^^^^
   |
   = help: add #![feature(proc_macro_hygiene)] to the crate attributes to enable

error[E0658]: procedural macros cannot be expanded to expressions (see issue #54727)
  --> /home/shannon/.cargo/registry/src/github.com-1ecc6299db9ec823/maud_macros-0.18.1/src/generate.rs:83:9
   |
83 | /         quote!({
84 | |             // Create a local trait alias so that autoref works
85 | |             trait Render: maud::Render {
86 | |                 fn __maud_render_to(&self, output_ident: &mut String) {
...  |
91 | |             $expr.__maud_render_to(&mut $output_ident);
92 | |         })
   | |__________^
   |
   = help: add #![feature(proc_macro_hygiene)] to the crate attributes to enable

error[E0658]: procedural macros cannot be expanded to expressions (see issue #54727)
   --> /home/shannon/.cargo/registry/src/github.com-1ecc6299db9ec823/maud_macros-0.18.1/src/generate.rs:140:25
    |
140 |                         quote!($head { $body })
    |                         ^^^^^^^^^^^^^^^^^^^^^^^
    |
    = help: add #![feature(proc_macro_hygiene)] to the crate attributes to enable

error[E0658]: procedural macros cannot be expanded to expressions (see issue #54727)
   --> /home/shannon/.cargo/registry/src/github.com-1ecc6299db9ec823/maud_macros-0.18.1/src/generate.rs:149:9
    |
149 |         quote!($head $body)
    |         ^^^^^^^^^^^^^^^^^^^
    |
    = help: add #![feature(proc_macro_hygiene)] to the crate attributes to enable

error[E0658]: procedural macros cannot be expanded to expressions (see issue #54727)
   --> /home/shannon/.cargo/registry/src/github.com-1ecc6299db9ec823/maud_macros-0.18.1/src/generate.rs:154:9
    |
154 |         quote!($head $body)
    |         ^^^^^^^^^^^^^^^^^^^
    |
    = help: add #![feature(proc_macro_hygiene)] to the crate attributes to enable

error[E0658]: procedural macros cannot be expanded to expressions (see issue #54727)
   --> /home/shannon/.cargo/registry/src/github.com-1ecc6299db9ec823/maud_macros-0.18.1/src/generate.rs:224:5
    |
224 |     quote!(if $cond)
    |     ^^^^^^^^^^^^^^^^
    |
    = help: add #![feature(proc_macro_hygiene)] to the crate attributes to enable

error[E0658]: procedural macros cannot be expanded to expressions (see issue #54727)
   --> /home/shannon/.cargo/registry/src/github.com-1ecc6299db9ec823/maud_macros-0.18.1/src/generate.rs:265:13
    |
265 |             quote!($output_ident.push_str($string);)
    |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = help: add #![feature(proc_macro_hygiene)] to the crate attributes to enable

error[E0658]: procedural macros cannot be expanded to expressions (see issue #54727)
  --> /home/shannon/.cargo/registry/src/github.com-1ecc6299db9ec823/maud_macros-0.18.1/src/lib.rs:50:5
   |
50 | /     quote!({
51 | |         extern crate maud;
52 | |         let mut $output_ident = String::with_capacity($size_hint);
53 | |         $stmts
54 | |         maud::PreEscaped($output_ident)
55 | |     })
   | |______^
   |
   = help: add #![feature(proc_macro_hygiene)] to the crate attributes to enable

error: aborting due to 9 previous errors

Some errors occurred: E0557, E0658.
For more information about an error, try `rustc --explain E0557`.
error: Could not compile `maud_macros`.
```
Running on cargo 1.31.0-nightly (ad6e5c003 2018-09-28).

Cheers!

**Comment by lfairy** [comment] 2018-10-11 08:06
Closing as duplicate of #151

**Closed by lfairy** 2018-10-11 08:06 UTC
Labels: duplicate

**Comment by TitanThinktank** [comment] 2019-05-15 12:50
15 | html! takes a single argume
   |             ^ expected `(` or `{`

error[E0658]: procedural macros cannot be expanded to expressions
  --> src/main.rs:9:18
   |
9  |       let markup = html! {
   |  __________________^
10 | |         p { "Hi, " (name) "!" }
11 | |     };
   | |_____^
   |
   = note: for more information, see https://github.com/rust-lang/rust/issues/54727
   = help: add #![feature(proc_macro_hygiene)] to the crate attributes to enable
