### ISSUE TITLE
proc-macro2?

### ISSUE THREAD

**Issue by ignatenkobrain** [lfairy/maud#115] opened 2018-01-14 11:43 UTC
I'm packaging systemd-manager which depends on horrorshow which depends on maud_macros in the end and right now maud_macros is nightly due to proc_macro.

Would it be possible to switch to proc-macro2 which is working under stable Rust?

https://crates.io/crates/proc-macro2

**Comment by lfairy** [comment] 2018-01-20 01:28
Yes it should be possible -- see #17.

The only issue with stable support is usability. Only custom derive is stable at the moment, so to use Maud under stable, you'll need to fiddle with build scripts and manual codegen. For this reason I haven't made stable support a priority yet.

Note that Horrorshow only depends on Maud for benchmarks. It should be safe to remove Maud from the dependencies as long as benchmarks are never built.

**Comment by ignatenkobrain** [comment] 2018-01-20 17:06
Oh, it seems I was blind when looking into horrorshow deps..

**Comment by lfairy** [comment] 2018-02-02 20:18
Closing as duplicate of #17.

**Closed by lfairy** 2018-02-02 20:18 UTC
